site_name: DAOModel
docs_dir: .

nav:
- Home: README.md
- Getting Started: docs/getting_started.md
- Usage:
  - DAO: docs/usage/dao.md
  - Model: docs/usage/model.md
  - Service: docs/usage/service.md
- Advanced:
  - Model Diff: docs/advanced/model_diff.md
- Additional Links:
  - GitHub Repo: https://github.com/BassMastaCod/DAOModel
  - PyPi Project: https://pypi.org/project/DAOModel/

theme: readthedocs
extra_css:
  - docs/style.css

plugins:
- same-dir
- search
- mkdocstrings:
    handlers:
      python:
        options:
          show_source: false
          heading_level: 4
          show_root_heading: true
          show_root_full_path: false
          separate_signature: true
          show_signature_annotations: true
          docstring_style: sphinx
          docstring_section_style: list
          list_style: spacy
          show_root_members_full_path: false
          members_order: source

markdown_extensions:
  - admonition
